### ISSUE TITLE
Good work! 

### ISSUE THREAD

**Issue by Atavic** [avuko/sb#1]
Jackladder uses SMTP on ports 13 and 25: https://github.com/x0rz/EQGRP/issues/33

Regarding your doubts about the choices for the targets, they all seem to have a mail server running and they belong to some big group with lot of networking. This makes them optimal choices for proxies, controlled by operational command consoles used on demand.

The geographical location follows what appears to be a rule for crime-related C2C (command & control) operations: keeping the number as sparse as possible with little differences between various countries. The interest for .ru and .cn is obvious, but there are also high numbers for .in and .pk (most probably a middle step for the focus on .cn)

**Comment by avuko** [comment]
I'll look into the mail server premise. However, I think I've also seen dns systems which probably didn't have mail running before the 'sendmail' implant. Anyway, more research ahead.

**Comment by avuko** [comment]
PS: Thanks for the feedback and suggestions, much appreciated :)

**Comment by Atavic** [comment]
Surely more research is needed, as more discussions about this (I see very little so far).
